export default Object.freeze({
  addMCQ: 'addMCQ',
  addCreateMaterialItem: "addCreateMaterialItem",
  replaceCreateMaterialItem: "replaceCreateMaterialItem",
  setMCQs: 'setMCQs',
  setMCQQuestions: 'setMCQQuestions',
  clearMaterialList: 'clearMaterialList',
  editMCQ: 'editMCQ',
  setProfileId: 'setProfileId',
  addImageToUploadQueue: 'addImageToUploadQueue',
  popImageFromUploadQueue: 'popImageFromUploadQueue',
  clearImageUploadQueue: 'clearImageUploadQueue',
  removeImageFromUploadQueue: 'removeImageFromUploadQueue',
  alterImageInUploadQueue: 'alterImageInUploadQueue',
  removeLastXFromUploadQueue: 'removeLastXFromUploadQueue',
});
