export default {
  id: 0,
  title: 'root',
  folders: [
    {
      id: 1,
      title: 'Math',
      folders: [
        {
          id: 2,
          title: 'Math 1',
          folders: [{ id: 4, title: 'Summaries', folders: [], posts: [] }],
          posts: [],
        },
        { id: 3, title: 'Math 2', folders: [], posts: [] },
      ],
      posts: [
        {
          id: 4,
          createdAt: '2021-09-22T16:38:43.252Z',
          updatedAt: '2021-11-02T23:27:27.245Z',
          title: 'my title 2',
          priceInCents: 0,
          commentCount: 3,
          subject: 'math d2',
          authorId: 40,
          rating: {
            id: 4,
            upvotes: 1,
            downvotes: 0,
            currentUserStatus: 'none',
          },
          materials: [
            {
              id: 2,
              materialType: 'mcq',
              title: 'Material Collecition 1',
              mcqs: [
                {
                  id: 2,
                  question: 'What is ur name?',
                  questionUriKey: null,
                  answerIndices: [1, 2],
                  choices: ['achilles221b', 'sameh', 'amir', 'engy'],
                  choicesUrisKeys: null,
                },
              ],
              flashcards: [],
              uris: [],
            },
          ],
          author: {
            id: 40,
            createdAt: '2021-09-22T15:45:33.513Z',
            updatedAt: '2021-09-22T20:12:50.310Z',
            name: 'Sameh Initial twe2lve',
            role: 'teacher',
            profilePicture: '',
            biography: 'Hi1',
          },
        },
      ],
    },
    {
      id: 5,
      title: 'Physics',
      folders: [],
      posts: [],
    },
    {
      id: 6,
      title: 'Test',
      folders: [],
      posts: [],
    },
  ],
  posts: [
    {
      id: 2,
      createdAt: '2021-09-10T12:44:57.292Z',
      updatedAt: '2021-10-31T16:01:09.737Z',
      title: 'my title 2',
      priceInCents: 0,
      commentCount: 1,
      subject: 'math d2',
      authorId: 109,
      rating: {
        id: 2,
        upvotes: 2,
        downvotes: 0,
        currentUserStatus: 'none',
      },
      materials: [],
      author: {
        id: 109,
        createdAt: '2021-10-24T07:48:35.226Z',
        updatedAt: '2021-10-24T07:48:38.577Z',
        name: 'Usvsh',
        role: 'student',
        profilePicture: '',
        biography: '',
      },
    },
    {
      id: 3,
      createdAt: '2021-09-22T16:29:36.523Z',
      updatedAt: '2021-10-31T15:48:11.400Z',
      title: 'my title 3',
      priceInCents: 0,
      commentCount: 2,
      subject: 'math d2',
      authorId: 80,
      rating: {
        id: 3,
        upvotes: 0,
        downvotes: 2,
        currentUserStatus: 'none',
      },
      materials: [
        {
          id: 87,
          materialType: 'mcq',
          title: 'Xx',
          mcqs: [
            {
              id: 98,
              question: 'Shzvsvs',
              questionUriKey: null,
              answerIndices: [0],
              choices: ['Xbsbsvs', 'Cxx'],
              choicesUrisKeys: null,
            },
            {
              id: 97,
              question: 'Sbvsavavsv',
              questionUriKey: null,
              answerIndices: [1],
              choices: ['Sshshsh', 'Dbdbsb'],
              choicesUrisKeys: null,
            },
          ],
          flashcards: [],
          uris: [],
        },
        {
          id: 88,
          materialType: 'mcq',
          title: 'Material Collecition 1',
          mcqs: [
            {
              id: 100,
              question: '88gigxibsubs7vs',
              questionUriKey: null,
              answerIndices: [0],
              choices: ['Hibsibs'],
              choicesUrisKeys: null,
            },
            {
              id: 99,
              question: 'What is ur name?',
              questionUriKey: null,
              answerIndices: [1, 2],
              choices: ['achilles221b', 'sameh', 'amir', 'engy'],
              choicesUrisKeys: null,
            },
          ],
          flashcards: [],
          uris: [],
        },
      ],
      author: {
        id: 80,
        createdAt: '2021-10-04T21:48:55.765Z',
        updatedAt: '2021-10-13T18:02:04.021Z',
        name: 'Sameh Initial twelسشسve',
        role: 'teacher',
        profilePicture: '',
        biography: 'Hلb',
      },
    },
  ],
};
